theme: jekyll-theme-minimal
title: Shalom Caruaru
description: [Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin arcu risus, maximus non ipsum ut, facilisis ullamcorper eros. Nulla non metus vitae orci pellentesque laoreet. Nunc vitae quam eu velit auctor gravida. Vestibulum vehicula porttitor ex, at placerat turpis. ]
logo: SHCaruaru.jpg
